import { useEffect, useId, useRef, useState, type KeyboardEvent } from 'react'

export interface SelectOption { value: string; label: string; count?: number }

export default function SelectMenu({ value, options, onChange, ariaLabel, className = '', searchable = false, searchPlaceholder = '搜索选项' }: { value: string; options: SelectOption[]; onChange: (value: string) => void; ariaLabel: string; className?: string; searchable?: boolean; searchPlaceholder?: string }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const [activeIndex, setActiveIndex] = useState(Math.max(0, options.findIndex((option) => option.value === value))); const rootRef = useRef<HTMLDivElement>(null); const searchRef = useRef<HTMLInputElement>(null); const listId = useId(); const selectedIndex = Math.max(0, options.findIndex((option) => option.value === value)); const selected = options[selectedIndex] || options[0]
  const filteredOptions = searchable && query.trim() ? options.filter((option) => option.label.toLowerCase().includes(query.trim().toLowerCase())) : options
  useEffect(() => { setActiveIndex(Math.max(0, filteredOptions.findIndex((option) => option.value === value))) }, [selectedIndex, value, query])
  useEffect(() => { if (open && searchable) searchRef.current?.focus() }, [open, searchable])
  useEffect(() => { if (!open) return undefined; const dismiss = (event: PointerEvent) => { if (!rootRef.current?.contains(event.target as Node)) setOpen(false) }; document.addEventListener('pointerdown', dismiss); return () => document.removeEventListener('pointerdown', dismiss) }, [open])
  const choose = (index: number) => { const option = filteredOptions[index]; if (!option) return; onChange(option.value); setOpen(false); setQuery('') }
  const onKeyDown = (event: KeyboardEvent<HTMLButtonElement | HTMLInputElement>) => { if (!open && (event.key === 'Enter' || event.key === ' ' || event.key === 'ArrowDown')) { event.preventDefault(); setOpen(true); return } if (!open) return; if (event.key === 'Escape') { event.preventDefault(); setOpen(false); setQuery('') } else if (event.key === 'ArrowDown') { event.preventDefault(); setActiveIndex((current) => Math.min(current + 1, filteredOptions.length - 1)) } else if (event.key === 'ArrowUp') { event.preventDefault(); setActiveIndex((current) => Math.max(current - 1, 0)) } else if (event.key === 'Home') { event.preventDefault(); setActiveIndex(0) } else if (event.key === 'End') { event.preventDefault(); setActiveIndex(filteredOptions.length - 1) } else if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); choose(activeIndex) } }
  return <div className={`select-menu ${className}`} ref={rootRef}><button className="select-trigger" type="button" aria-label={ariaLabel} aria-haspopup="listbox" aria-expanded={open} aria-controls={listId} onClick={() => setOpen((current) => !current)} onKeyDown={onKeyDown}><span>{selected?.label || '请选择'}</span>{selected?.count !== undefined && <small>{selected.count}</small>}<span className={`select-chevron ${open ? 'open' : ''}`} aria-hidden="true" /></button>{open && <div className="select-menu-list" id={listId} role="listbox" aria-label={ariaLabel}>{searchable && <div className="select-search"><input ref={searchRef} value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={onKeyDown} placeholder={searchPlaceholder} aria-label={searchPlaceholder} /></div>}{filteredOptions.length ? filteredOptions.map((option, index) => <button className={`select-menu-option ${option.value === value ? 'selected' : ''} ${index === activeIndex ? 'active' : ''}`} type="button" role="option" aria-selected={option.value === value} key={option.value} onMouseEnter={() => setActiveIndex(index)} onClick={() => choose(index)}><span>{option.label}</span>{option.count !== undefined && <small>{option.count}</small>}</button>) : <div className="select-no-results">没有匹配选项</div>}</div>}</div>
}
